version: '3'

networks:
  www:

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
     - "80:80"
     - "8000-8020:8000-8020"

    volumes: 
     - "${VOLUMES_ROOT}/nginx/conf:/etc/nginx/conf.d"
     - "${VOLUMES_ROOT}/nginx/log:/var/log/nginx"
     - "${VOLUMES_ROOT}/www:/var/www/html"
    depends_on:
      - php
      - mysql
    networks:
      - www

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    tty: true
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password --sql_mode=""
    ports:
      - "4306:3306"
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - "${VOLUMES_ROOT}/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "${VOLUMES_ROOT}/mysql/log:/var/log/mysql"
      - "${VOLUMES_ROOT}/mysql/data:/var/lib/mysql"
    networks:
      - www

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - "${VOLUMES_ROOT}/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "${VOLUMES_ROOT}/www:/var/www/html"
    ports: 
      - "9009:9000"
    environment: 
      TZ: ${TZ}
    networks:
     - www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "81:80"
    environment:
      PMA_HOST: ${HOST}
      PMA_PORT: 3306