version: '3'

networks:
  www:

services:
  nginx:
    restart: always
    image: nginx:alpine
    volumes: 
      - "${VOLUMES_ROOT}/services/nginx/conf.d/template:/etc/nginx/templates"
      - "${VOLUMES_ROOT}/log/nginx:/var/log/nginx"
      - "${VOLUMES_ROOT}/www:/var/www/html"
    environment:
      LOG_ROOT: /var/log/nginx
    ports:
      - "71:71"
      - "74:74"
      - "8000-8030:8000-8030"
    depends_on:
      - php71
      - php74
      - mysql57
      - mysql80
      - redis
    networks:
      - www

  mysql57:
    image: mysql:5.7
    restart: always
    tty: true
    command: mysqld --sql_mode=""
    volumes:
      - "${VOLUMES_ROOT}/services/mysql/5.7/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "${VOLUMES_ROOT}/log/mysql/5.7:/var/log/mysql"
      - "${VOLUMES_ROOT}/data/mysql/5.7:/var/lib/mysql"
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${MYSQL_57_PORT}:3306"
    networks:
      - www

  mysql80:
    image: mysql:8.0
    restart: always
    tty: true
    command: mysqld --sql_mode=""
    volumes:
      - "${VOLUMES_ROOT}/services/mysql/8.0/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "${VOLUMES_ROOT}/log/mysql/8.0:/var/log/mysql"
      - "${VOLUMES_ROOT}/data/mysql/8.0:/var/lib/mysql"
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${MYSQL_80_PORT}:3306"
    networks:
      - www

  php71:
    build:
      context: .
      dockerfile: ${VOLUMES_ROOT}/services/php/7.1/dockerfile/Dockerfile
    volumes:
      - "${VOLUMES_ROOT}/services/php/7.1/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "${VOLUMES_ROOT}/www:/var/www/html"
      - "${VOLUMES_ROOT}/log/php/7.1:/var/log/php"
    environment: 
      HOST: ${HOST}
      LOG_ROOT: /var/log/php
      TZ: ${TZ}
    networks:
      - www

  php74:
    build:
      context: .
      dockerfile: ${VOLUMES_ROOT}/services/php/7.4/dockerfile/Dockerfile
    volumes:
      - "${VOLUMES_ROOT}/services/php/7.4/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "${VOLUMES_ROOT}/www:/var/www/html"
      - "${VOLUMES_ROOT}/log/php/7.4:/var/log/php"
    environment: 
      HOST: ${HOST}
      LOG_ROOT: /var/log/php
      TZ: ${TZ}
    networks:
      - www

  redis:
    image: redis:alpine
    volumes:
      - "${VOLUMES_ROOT}/services/redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "${VOLUMES_ROOT}/log/redis:/var/log/redis"
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: "${HOST},${HOST}"
      PMA_PORTS: "${MYSQL_57_PORT},${MYSQL_80_PORT}"
      PMA_VERBOSES: "mysql-5.7,mysql-8.0"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql57
      - mysql80
  
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    ports:
      - "${REDISMYADMIN_PORT}:80"
    depends_on:
      - redis
    networks:
      - www