version: '3'

networks:
  www:

services:
  nginx:
    restart: always
    image: nginx:alpine
    container_name: ${NGINX_NAME}
    volumes: 
      - "${VOLUMES_ROOT}/nginx/conf.d/template:/etc/nginx/templates"
      - "${VOLUMES_ROOT}/nginx/log:/var/log/nginx"
      - "${VOLUMES_ROOT}/www:/var/www/html"
    environment:
      PHP_NAME: ${PHP_NAME}
      LOG_ROOT: /var/log/nginx
    ports:
      - "80:80"
      - "8000-8020:8000-8020"
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - www

  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_NAME}
    restart: always
    tty: true
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - "${VOLUMES_ROOT}/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "${VOLUMES_ROOT}/mysql/log:/var/log/mysql"
      - "${VOLUMES_ROOT}/mysql/data:/var/lib/mysql"
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - www

  php:
    build:
      context: .
      dockerfile: ${PHP_DOCKERFILE}
    container_name: ${PHP_NAME}
    volumes:
      - "${VOLUMES_ROOT}/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "${VOLUMES_ROOT}/www:/var/www/html"
      - "${VOLUMES_ROOT}/php/log:/var/log/php"
    environment: 
      HOST: ${HOST}
      LOG_ROOT: /var/log/php
      TZ: ${TZ}
    networks:
      - www

  redis:
    image: redis:alpine
    container_name: ${REDIS_NAME}
    volumes:
      - "${VOLUMES_ROOT}/redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "${VOLUMES_ROOT}/redis/log:/var/log/redis"
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PHPMYADMIN_NAME}
    environment:
      PMA_HOST: ${HOST}
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql